export const portfolioProjects = [
  {
    id: 1,
    titleAr: 'جناح أرامكو - معرض الطاقة الدولي',
    titleEn: 'Saudi Aramco Stand - International Energy Exhibition',
    categoryAr: 'أجنحة مخصصة',
    categoryEn: 'Custom Stands',
    year: 2024,
    area: '500 م²',
    client: 'Saudi Aramco',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    featured: true,
  },
  {
    id: 2,
    titleAr: 'جناح stc - جيتكس 2024',
    titleEn: 'stc Stand - GITEX 2024',
    categoryAr: 'أجنحة مخصصة',
    categoryEn: 'Custom Stands',
    year: 2024,
    area: '300 م²',
    client: 'STC',
    image: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800&q=80',
    featured: true,
  },
  {
    id: 3,
    titleAr: 'جناح صندوق الاستثمارات - منتدى مستقبل الاستثمار',
    titleEn: 'PIF Stand - Future Investment Initiative',
    categoryAr: 'إنتاج الفعاليات',
    categoryEn: 'Event Production',
    year: 2024,
    area: '1000 م²',
    client: 'Public Investment Fund',
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&q=80',
    featured: true,
  },
  {
    id: 4,
    titleAr: 'مؤتمر قمة مستقبل الاستثمار',
    titleEn: 'Future Investment Initiative Summit',
    categoryAr: 'إدارة المؤتمرات',
    categoryEn: 'Conference Management',
    year: 2023,
    area: '5000 م²',
    client: 'Ministry of Investment',
    image: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&q=80',
    featured: false,
  },
  {
    id: 5,
    titleAr: 'جناح نيوم - معرض البيج فايف',
    titleEn: 'NEOM Stand - Big 5 Saudi',
    categoryAr: 'أجنحة مخصصة',
    categoryEn: 'Custom Stands',
    year: 2023,
    area: '400 م²',
    client: 'NEOM',
    image: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?w=800&q=80',
    featured: false,
  },
  {
    id: 6,
    titleAr: 'تفعيل علامة بنك الراجحي',
    titleEn: 'Al Rajhi Bank Brand Activation',
    categoryAr: 'تفعيل العلامات التجارية',
    categoryEn: 'Brand Activations',
    year: 2023,
    area: '200 م²',
    client: 'Al Rajhi Bank',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    featured: false,
  },
  {
    id: 7,
    titleAr: 'جناح سابك - معرض الكيمياء الدولي',
    titleEn: 'SABIC Stand - International Chemistry Exhibition',
    categoryAr: 'أجنحة مخصصة',
    categoryEn: 'Custom Stands',
    year: 2023,
    area: '600 م²',
    client: 'SABIC',
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80',
    featured: false,
  },
  {
    id: 8,
    titleAr: 'فعالية اليوم الوطني السعودي',
    titleEn: 'Saudi National Day Event',
    categoryAr: 'إنتاج الفعاليات',
    categoryEn: 'Event Production',
    year: 2024,
    area: '3000 م²',
    client: 'Ministry of Culture',
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80',
    featured: false,
  },
];

export const clients = [
  { nameAr: 'مدينة الملك عبدالعزيز للعلوم والتقنية', nameEn: 'KACST', sector: 'government', logo: '/clients/kacst.png' },
  { nameAr: 'غرفة الرياض', nameEn: 'Riyadh Chamber', sector: 'government', logo: '/clients/riyadh-chamber.png' },
  { nameAr: 'هيئة تطوير منطقة المدينة المنورة', nameEn: 'Al Madinah Region Development Authority', sector: 'government', logo: '/clients/madinah-authority.png' },
  { nameAr: 'الجمعية الخيرية لرعاية الأيتام - إنسان', nameEn: 'Charity Committee for Orphans Care', sector: 'nonprofit', logo: '/clients/ensan.png' },
  { nameAr: 'وزارة المالية', nameEn: 'Ministry of Finance', sector: 'government', logo: '/clients/ministry-finance.png' },
  { nameAr: 'سمة - السعودية للمعلومات الائتمانية', nameEn: 'SIMAH', sector: 'finance', logo: '/clients/simah.png' },
  { nameAr: 'ملتقى ألوان السعودية', nameEn: 'Colors of Saudi Arabia Forum', sector: 'culture', logo: '/clients/colors-ksa.png' },
  { nameAr: 'وزارة الصحة', nameEn: 'Ministry of Health', sector: 'government', logo: '/clients/ministry-health.png' },
  { nameAr: 'وزارة الدفاع', nameEn: 'Ministry of Defense', sector: 'government', logo: '/clients/ministry-defense.png' },
  { nameAr: 'وزارة التعليم', nameEn: 'Ministry of Education', sector: 'government', logo: '/clients/ministry-education.png' },
  { nameAr: 'حياك لاونج', nameEn: 'Hayyak Lounge', sector: 'hospitality', logo: '/clients/hayyak.png' },
  { nameAr: 'stc', nameEn: 'stc', sector: 'tech', logo: '/clients/stc.png' },
  { nameAr: 'SIDMC', nameEn: 'SIDMC', sector: 'tech', logo: '/clients/sidmc.png' },
];

export const testimonials = [
  {
    nameAr: 'محمد العتيبي',
    nameEn: 'Mohammed Al-Otaibi',
    titleAr: 'مدير التسويق - شركة الاتصالات السعودية',
    titleEn: 'Marketing Director - STC',
    textAr: 'تجربة رائعة مع إكسبو تايم. الجناح كان استثنائياً وجذب اهتمام كبير من الزوار. الفريق محترف جداً ويتعامل مع كل التفاصيل باحترافية عالية.',
    textEn: 'An amazing experience with Expo Time. The stand was exceptional and attracted significant attention from visitors. The team is very professional and handles every detail with high professionalism.',
    rating: 5,
  },
  {
    nameAr: 'سارة الغامدي',
    nameEn: 'Sarah Al-Ghamdi',
    titleAr: 'مدير الفعاليات - مجموعة أعمار',
    titleEn: 'Events Director - Emaar Group',
    textAr: 'نعمل مع إكسبو تايم منذ 5 سنوات وهم دائماً يتجاوزون توقعاتنا. الجودة والإبداع والالتزام بالمواعيد من أبرز ما يميزهم.',
    textEn: 'We have been working with Expo Time for 5 years and they always exceed our expectations. Quality, creativity, and commitment to deadlines are their most distinctive traits.',
    rating: 5,
  },
  {
    nameAr: 'فهد الشمري',
    nameEn: 'Fahad Al-Shammari',
    titleAr: 'مسؤول المعارض - أرامكو السعودية',
    titleEn: 'Exhibitions Manager - Saudi Aramco',
    textAr: 'أفضل شركة تصميم أجنحة في المملكة العربية السعودية. يفهمون احتياجات العميل ويقدمون حلولاً إبداعية تعكس هوية العلامة التجارية بشكل مثالي.',
    textEn: 'The best exhibition stand design company in Saudi Arabia. They understand client needs and deliver creative solutions that perfectly reflect brand identity.',
    rating: 5,
  },
  {
    nameAr: 'نورة القحطاني',
    nameEn: 'Noura Al-Qahtani',
    titleAr: 'مديرة التسويق - وزارة الثقافة',
    titleEn: 'Marketing Director - Ministry of Culture',
    textAr: 'إكسبو تايم حولت فكرتنا إلى واقع مبهر. الفريق متعاون ومبدع وملتزم بالجودة في كل خطوة من خطوات التنفيذ.',
    textEn: 'Expo Time turned our idea into a stunning reality. The team is collaborative, creative, and committed to quality at every step of execution.',
    rating: 5,
  },
];

export const blogPosts = [
  {
    slug: 'exhibition-stand-design-trends-2026',
    titleAr: 'أبرز اتجاهات تصميم أجنحة المعارض في 2026',
    titleEn: 'Top Exhibition Stand Design Trends in 2026',
    excerptAr: 'اكتشف أحدث اتجاهات تصميم أجنحة المعارض لعام 2026، من الخشب المستدام إلى تقنيات الواقع الافتراضي والتفاعلية',
    excerptEn: 'Discover the latest exhibition stand design trends for 2026, from sustainable materials to VR technology and interactive experiences',
    categoryAr: 'تصميم الأجنحة',
    categoryEn: 'Stand Design',
    date: '2026-03-15',
    readTimeAr: '5 دقائق قراءة',
    readTimeEn: '5 min read',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    contentAr: `<h2>مقدمة</h2><p>صناعة المعارض تتطور بسرعة، وعام 2026 يشهد ثورة حقيقية في تصميم الأجنحة. من التصاميم المستدامة إلى التكنولوجيا التفاعلية، هذه أبرز الاتجاهات التي ستهيمن على المشهد.</p><h2>1. الاستدامة والمواد الصديقة للبيئة</h2><p>تشهد صناعة المعارض تحولاً كبيراً نحو الاستدامة، مع تزايد الطلب على المواد القابلة لإعادة التدوير والأجنحة القابلة لإعادة الاستخدام.</p><h2>2. التكنولوجيا التفاعلية والواقع الافتراضي</h2><p>شاشات LED الضخمة، وتقنيات AR/VR، والكشك التفاعلية أصبحت ضرورة لا رفاهية في أجنحة 2026.</p>`,
    contentEn: `<h2>Introduction</h2><p>The exhibition industry is evolving rapidly, and 2026 is witnessing a real revolution in stand design. From sustainable designs to interactive technology, these are the top trends.</p><h2>1. Sustainability and Eco-Friendly Materials</h2><p>The exhibition industry is undergoing a major shift toward sustainability, with growing demand for recyclable materials and reusable stands.</p><h2>2. Interactive Technology and Virtual Reality</h2><p>Large LED screens, AR/VR technologies, and interactive kiosks have become a necessity in 2026 stands.</p>`,
  },
  {
    slug: 'how-to-maximize-roi-at-exhibitions',
    titleAr: 'كيف تحقق أقصى عائد من مشاركتك في المعارض؟',
    titleEn: 'How to Maximize Your ROI at Exhibitions',
    excerptAr: 'دليل شامل لتحقيق أفضل النتائج من مشاركتك في المعارض التجارية',
    excerptEn: 'A comprehensive guide to achieving the best results from your trade show participation',
    categoryAr: 'نصائح المعارض',
    categoryEn: 'Exhibition Tips',
    date: '2026-02-20',
    readTimeAr: '8 دقائق قراءة',
    readTimeEn: '8 min read',
    image: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800&q=80',
    contentAr: `<h2>لماذا تحتاج إلى استراتيجية واضحة؟</h2><p>المشاركة في المعارض استثمار كبير، ولتحقيق أعلى عائد يجب أن يكون لديك استراتيجية محكمة قبل المعرض وأثناءه وبعده.</p>`,
    contentEn: `<h2>Why Do You Need a Clear Strategy?</h2><p>Exhibition participation is a major investment, and to achieve the highest return you need a solid strategy before, during, and after the exhibition.</p>`,
  },
  {
    slug: 'riyadh-exhibitions-calendar-2026',
    titleAr: 'تقويم المعارض في الرياض لعام 2026',
    titleEn: 'Riyadh Exhibitions Calendar 2026',
    excerptAr: 'أهم المعارض والفعاليات المقررة في الرياض خلال عام 2026',
    excerptEn: 'Key exhibitions and events scheduled in Riyadh during 2026',
    categoryAr: 'أخبار المعارض',
    categoryEn: 'Exhibition News',
    date: '2026-01-10',
    readTimeAr: '6 دقائق قراءة',
    readTimeEn: '6 min read',
    image: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&q=80',
    contentAr: `<h2>المعارض الكبرى في الرياض 2026</h2><p>الرياض تستضيف عشرات المعارض الدولية الكبرى سنوياً. هذا دليلك الشامل بأهم الفعاليات.</p>`,
    contentEn: `<h2>Major Exhibitions in Riyadh 2026</h2><p>Riyadh hosts dozens of major international exhibitions annually. This is your comprehensive guide to the most important events.</p>`,
  },
  {
    slug: 'custom-vs-modular-stands',
    titleAr: 'الأجنحة المخصصة مقابل النمطية: أيهما أفضل؟',
    titleEn: 'Custom vs Modular Stands: Which is Right for You?',
    excerptAr: 'مقارنة شاملة لمساعدتك في اتخاذ القرار الصحيح',
    excerptEn: 'A comprehensive comparison to help you make the right decision',
    categoryAr: 'تصميم الأجنحة',
    categoryEn: 'Stand Design',
    date: '2025-12-05',
    readTimeAr: '7 دقائق قراءة',
    readTimeEn: '7 min read',
    image: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?w=800&q=80',
    contentAr: `<h2>الأجنحة المخصصة</h2><p>الأجنحة المخصصة مصممة خصيصاً لعلامتك التجارية وتعكس هويتها بشكل فريد، لكنها تكلف أكثر وتحتاج وقتاً أطول للتصنيع.</p>`,
    contentEn: `<h2>Custom Stands</h2><p>Custom stands are designed specifically for your brand and uniquely reflect its identity, but they cost more and require longer manufacturing time.</p>`,
  },
];

export const faqs = {
  ar: [
    {
      q: 'كم تستغرق عملية تصميم وتنفيذ جناح المعرض؟',
      a: 'تستغرق عملية التصميم والتنفيذ عادةً من 4 إلى 8 أسابيع، حسب حجم الجناح وتعقيده. نوصي بالتواصل معنا قبل 3 أشهر على الأقل من موعد المعرض.',
    },
    {
      q: 'هل تقدمون خدماتكم في جميع مدن المملكة؟',
      a: 'نعم، نخدم جميع مدن المملكة العربية السعودية بما فيها الرياض وجدة والدمام والخبر ومكة المكرمة والمدينة المنورة ونيوم والمنطقة الشرقية.',
    },
    {
      q: 'ما أنواع الأجنحة التي تصممونها؟',
      a: 'نصمم وننفذ جميع أنواع الأجنحة: الأجنحة المخصصة، الأجنحة النمطية، الأجنحة مزدوجة الطابق، أجنحة الشل سكيم، والهياكل المؤقتة للفعاليات الخارجية.',
    },
    {
      q: 'هل تقدمون خدمة التركيب والفك والشحن؟',
      a: 'نعم، نقدم خدمة شاملة تشمل التصميم والتصنيع والشحن والتركيب والفك بعد المعرض مع ضمان سلامة جميع العناصر.',
    },
    {
      q: 'كيف يمكنني الحصول على عرض سعر؟',
      a: 'يمكنك التواصل معنا عبر نموذج الاتصال أو الاتصال المباشر على +966 11 239 3255. سنتواصل معك خلال 24 ساعة بعرض سعر مفصل.',
    },
    {
      q: 'هل تعملون في المعارض الدولية خارج المملكة؟',
      a: 'نعم، نقدم خدماتنا في المعارض الدولية الكبرى في دول الخليج والشرق الأوسط وأوروبا وآسيا.',
    },
  ],
  en: [
    {
      q: 'How long does it take to design and build an exhibition stand?',
      a: 'The design and build process typically takes 4 to 8 weeks, depending on the stand size and complexity. We recommend contacting us at least 3 months before your exhibition date.',
    },
    {
      q: 'Do you serve all cities in Saudi Arabia?',
      a: 'Yes, we serve all Saudi cities including Riyadh, Jeddah, Dammam, Khobar, Makkah, Madinah, NEOM, and the Eastern Province.',
    },
    {
      q: 'What types of stands do you design?',
      a: 'We design and build all types of stands: custom stands, modular stands, double-decker stands, shell scheme stands, and temporary structures for outdoor events.',
    },
    {
      q: 'Do you provide installation, dismantling, and shipping services?',
      a: 'Yes, we provide a comprehensive service including design, manufacturing, shipping, installation, and post-show dismantling with guaranteed safety of all components.',
    },
    {
      q: 'How can I get a quote?',
      a: 'You can contact us via the contact form or call us directly at +966 11 239 3255. We will get back to you within 24 hours with a detailed quote.',
    },
    {
      q: 'Do you work at international exhibitions outside Saudi Arabia?',
      a: 'Yes, we provide our services at major international exhibitions in GCC countries, the Middle East, Europe, and Asia.',
    },
  ],
};

export const services = [
  {
    slug: 'exhibition-stand-design',
    icon: '🎨',
    titleAr: 'تصميم أجنحة المعارض',
    titleEn: 'Exhibition Stand Design',
    descAr: 'نصمم أجنحة معارض استثنائية تعكس هوية علامتك التجارية بتصاميم ثلاثية الأبعاد احترافية',
    descEn: 'We design extraordinary exhibition stands that reflect your brand identity with professional 3D visualizations',
    color: 'from-amber-500 to-orange-600',
  },
  {
    slug: 'exhibition-booth-fabrication',
    icon: '🔧',
    titleAr: 'تنفيذ وتصنيع الأجنحة',
    titleEn: 'Exhibition Booth Fabrication',
    descAr: 'تصنيع وتنفيذ أجنحة المعارض بأعلى معايير الجودة باستخدام أحدث المواد والتقنيات',
    descEn: 'Manufacturing and fabricating exhibition stands with the highest quality standards using the latest materials and techniques',
    color: 'from-blue-500 to-cyan-600',
  },
  {
    slug: 'exhibition-contractor',
    icon: '🏗️',
    titleAr: 'مقاول المعارض',
    titleEn: 'Exhibition Contractor',
    descAr: 'خدمات مقاولة شاملة لجميع أعمال التركيب والبناء في المعارض والفعاليات',
    descEn: 'Comprehensive contracting services for all installation and construction work at exhibitions and events',
    color: 'from-emerald-500 to-teal-600',
  },
  {
    slug: 'conference-management',
    icon: '🎤',
    titleAr: 'إدارة المؤتمرات',
    titleEn: 'Conference Management',
    descAr: 'تنظيم مؤتمرات ومنتديات بمستوى عالمي مع حلول صوتية وبصرية متكاملة',
    descEn: 'World-class conference and forum organization with integrated audio-visual solutions',
    color: 'from-purple-500 to-violet-600',
  },
  {
    slug: 'event-management',
    icon: '📅',
    titleAr: 'إدارة الفعاليات',
    titleEn: 'Event Management',
    descAr: 'إدارة متكاملة لفعالياتك من التخطيط إلى التنفيذ مع فريق متخصص وخبرة واسعة',
    descEn: 'Complete event management from planning to execution with a specialized team and extensive experience',
    color: 'from-rose-500 to-pink-600',
  },
  {
    slug: 'event-production',
    icon: '🎬',
    titleAr: 'إنتاج الفعاليات',
    titleEn: 'Event Production',
    descAr: 'إنتاج متكامل للفعاليات يشمل الصوت والإضاءة والديكور وإدارة اللوجستيات',
    descEn: 'Comprehensive event production including sound, lighting, décor, and logistics management',
    color: 'from-indigo-500 to-blue-600',
  },
  {
    slug: 'exhibition-services',
    icon: '⭐',
    titleAr: 'خدمات المعارض الشاملة',
    titleEn: 'Exhibition Services',
    descAr: 'باقة شاملة من خدمات المعارض تغطي جميع احتياجاتك من الألف إلى الياء',
    descEn: 'A comprehensive package of exhibition services covering all your needs from A to Z',
    color: 'from-yellow-500 to-amber-600',
  },
  {
    slug: 'custom-booths',
    icon: '✏️',
    titleAr: 'الأجنحة المخصصة',
    titleEn: 'Custom Booths',
    descAr: 'أجنحة مصممة خصيصاً لتلبية احتياجاتك مع أعلى معايير الجودة في التنفيذ والتشطيب',
    descEn: 'Bespoke booths designed specifically to meet your requirements with the highest quality standards',
    color: 'from-teal-500 to-green-600',
  },
  {
    slug: 'modular-booths',
    icon: '🧩',
    titleAr: 'الأجنحة النمطية',
    titleEn: 'Modular Booths',
    descAr: 'حلول مرنة وقابلة للتوسع توفر أفضل قيمة مقابل التكلفة للمشاركة في معارض متعددة',
    descEn: 'Flexible and scalable solutions that deliver the best value for participating in multiple exhibitions',
    color: 'from-orange-500 to-red-600',
  },
  {
    slug: 'temporary-structures',
    icon: '🏛️',
    titleAr: 'الهياكل المؤقتة',
    titleEn: 'Temporary Structures',
    descAr: 'هياكل مؤقتة عالية الجودة للمعارض الخارجية والفعاليات الكبرى والخيام الضخمة',
    descEn: 'High-quality temporary structures for outdoor exhibitions, large-scale events, and large tents',
    color: 'from-slate-500 to-gray-600',
  },
  {
    slug: 'brand-activations',
    icon: '⚡',
    titleAr: 'تفعيل العلامات التجارية',
    titleEn: 'Brand Activations',
    descAr: 'تجارب تفاعلية مبتكرة تعزز حضور علامتك التجارية وتخلق انطباعاً لا يُنسى',
    descEn: 'Innovative interactive experiences that enhance your brand presence and create unforgettable impressions',
    color: 'from-fuchsia-500 to-purple-600',
  },
];

export const cities = [
  {
    slug: 'riyadh',
    nameAr: 'الرياض',
    nameEn: 'Riyadh',
    descAr: 'العاصمة ومركز الأعمال الرئيسي في المملكة العربية السعودية',
    descEn: 'The capital and main business hub of Saudi Arabia',
    venues: ['مركز الرياض الدولي للمؤتمرات والمعارض', 'ميدان إكسبو', 'أرينا درعية'],
    venuesEn: ['Riyadh International Convention Center', 'Expo Riyadh', 'Diriyah Arena'],
    population: '7.5 مليون',
    image: 'https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?w=800&q=80',
  },
  {
    slug: 'jeddah',
    nameAr: 'جدة',
    nameEn: 'Jeddah',
    descAr: 'البوابة التجارية للمملكة والعاصمة الاقتصادية غير الرسمية',
    descEn: 'The commercial gateway and unofficial economic capital of Saudi Arabia',
    venues: ['مركز جدة الدولي للمعارض والمؤتمرات', 'جدة سوبر دوم'],
    venuesEn: ['Jeddah International Exhibition & Conference Center', 'Jeddah Super Dome'],
    population: '4.7 مليون',
    image: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=800&q=80',
  },
  {
    slug: 'dammam',
    nameAr: 'الدمام',
    nameEn: 'Dammam',
    descAr: 'عاصمة المنطقة الشرقية ومركز صناعة النفط والغاز',
    descEn: 'Capital of the Eastern Province and oil and gas industry hub',
    venues: ['مركز الدمام الدولي للمعارض والمؤتمرات'],
    venuesEn: ['Dammam International Exhibition and Convention Center'],
    population: '1.5 مليون',
    image: 'https://images.unsplash.com/photo-1611516491426-03025e6043c8?w=800&q=80',
  },
  {
    slug: 'khobar',
    nameAr: 'الخبر',
    nameEn: 'Khobar',
    descAr: 'مدينة الأعمال الحديثة في المنطقة الشرقية',
    descEn: 'The modern business city in the Eastern Province',
    venues: ['فندق لو ميريديان الخبر', 'إنتركونتيننتال الخبر'],
    venuesEn: ['Le Meridien Al Khobar', 'InterContinental Al Khobar'],
    population: '1.1 مليون',
    image: 'https://images.unsplash.com/photo-1535132011086-b8818f016104?w=800&q=80',
  },
  {
    slug: 'makkah',
    nameAr: 'مكة المكرمة',
    nameEn: 'Makkah',
    descAr: 'أقدس مدينة في الإسلام وجهة الملايين سنوياً',
    descEn: 'The holiest city in Islam and destination of millions annually',
    venues: ['مركز الملك عبدالعزيز للمؤتمرات', 'مجمع أبراج البيت'],
    venuesEn: ['King Abdul Aziz Convention Center', 'Abraj Al-Bait Complex'],
    population: '2 مليون',
    image: 'https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=800&q=80',
  },
  {
    slug: 'madinah',
    nameAr: 'المدينة المنورة',
    nameEn: 'Madinah',
    descAr: 'مدينة النور والروحانية والثقافة الإسلامية',
    descEn: 'City of light, spirituality, and Islamic culture',
    venues: ['فندق هيلتون المدينة', 'أوبيروي المدينة المنورة'],
    venuesEn: ['Madinah Hilton', 'Oberoi Madinah'],
    population: '1.3 مليون',
    image: 'https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?w=800&q=80',
  },
  {
    slug: 'neom',
    nameAr: 'نيوم',
    nameEn: 'NEOM',
    descAr: 'مدينة المستقبل الأكثر طموحاً في العالم',
    descEn: "The world's most ambitious city of the future",
    venues: ['مركز معارض نيوم', 'مركز فعاليات ذا لاين'],
    venuesEn: ['NEOM Exhibition Hub', 'The LINE Events Center'],
    population: 'مشروع المستقبل',
    image: 'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?w=800&q=80',
  },
  {
    slug: 'eastern-province',
    nameAr: 'المنطقة الشرقية',
    nameEn: 'Eastern Province',
    descAr: 'قلب صناعة النفط والغاز والبتروكيماويات في المملكة',
    descEn: "The heart of Saudi Arabia's oil, gas, and petrochemical industry",
    venues: ['مركز الدمام للمعارض', 'مركز الجبيل للمعارض'],
    venuesEn: ['Dammam Exhibition Center', 'Jubail Exhibition Center'],
    population: '4.9 مليون',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
  },
];

export const industries = [
  { icon: '💻', slugAr: 'التقنية', slugEn: 'tech', nameAr: 'التقنية والابتكار', nameEn: 'Technology & Innovation' },
  { icon: '🏥', slugAr: 'الصحة', slugEn: 'health', nameAr: 'الرعاية الصحية', nameEn: 'Healthcare' },
  { icon: '🏗️', slugAr: 'البناء', slugEn: 'construction', nameAr: 'البناء والتشييد', nameEn: 'Construction & Real Estate' },
  { icon: '🍽️', slugAr: 'الغذاء', slugEn: 'food', nameAr: 'الغذاء والضيافة', nameEn: 'Food & Hospitality' },
  { icon: '🚗', slugAr: 'السيارات', slugEn: 'auto', nameAr: 'السيارات', nameEn: 'Automotive' },
  { icon: '💰', slugAr: 'المال', slugEn: 'finance', nameAr: 'المال والأعمال', nameEn: 'Finance & Business' },
  { icon: '⚡', slugAr: 'الطاقة', slugEn: 'energy', nameAr: 'الطاقة والبيئة', nameEn: 'Energy & Environment' },
  { icon: '📚', slugAr: 'التعليم', slugEn: 'education', nameAr: 'التعليم والتدريب', nameEn: 'Education & Training' },
  { icon: '🛍️', slugAr: 'التجزئة', slugEn: 'retail', nameAr: 'التجزئة والأزياء', nameEn: 'Retail & Fashion' },
  { icon: '🏛️', slugAr: 'الحكومة', slugEn: 'government', nameAr: 'القطاع الحكومي', nameEn: 'Government Sector' },
];
