import type { Metadata } from 'next';
import ServicePageTemplate from '@/components/ServicePageTemplate';
import { generatePageMetadata } from '@/lib/seo';
type Props = { params: Promise<{ locale: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params;
  return generatePageMetadata(locale,'الأجنحة المخصصة في الرياض | إكسبو تايم','Custom Exhibition Booths Riyadh | Expo Time','إكسبو تايم متخصصون في تصميم وتنفيذ الأجنحة المخصصة في الرياض والمملكة العربية السعودية بأعلى معايير الجودة والإبداع','Expo Time specializes in designing and fabricating custom exhibition booths in Riyadh and Saudi Arabia with the highest quality and creativity standards','/custom-booths');
}
export default async function CustomBoothsPage({ params }: Props) {
  const { locale } = await params;
  return (<ServicePageTemplate locale={locale} titleAr="الأجنحة المخصصة في المعارض" titleEn="Custom Exhibition Booths" subtitleAr="أجنحة مصممة خصيصاً لعلامتك التجارية بتصاميم فريدة تعكس هويتك وتميزك عن المنافسين في أي معرض" subtitleEn="Booths designed exclusively for your brand with unique designs that reflect your identity and differentiate you from competitors at any exhibition" descAr="الأجنحة المخصصة هي التعبير الأمثل عن هوية علامتك التجارية في عالم المعارض. في إكسبو تايم، نصمم ونبني أجنحة فريدة من نوعها تبدأ من صفحة بيضاء تماماً، حيث يعمل فريقنا من المصممين والمهندسين المتخصصين على ترجمة رؤيتك إلى واقع ملموس يفوق توقعاتك." descEn="Custom booths are the ultimate expression of your brand identity in the world of exhibitions. At Expo Time, we design and build truly unique booths that start from a completely blank canvas, where our team of specialized designers and engineers works to translate your vision into a tangible reality that exceeds your expectations." featuresAr={['تصميم فريد يعكس هويتك التجارية بدقة','تصنيع بأعلى معايير الجودة والمتانة','استخدام أفخم المواد والتشطيبات','إضاءة مدروسة لإبراز منتجاتك','مساحات تفاعلية وغرف اجتماعات','تركيب وفك احترافي','ضمان شامل على جميع العناصر','خدمة ما بعد المعرض']} featuresEn={['Unique design that accurately reflects your brand identity','Manufacturing with highest quality and durability standards','Use of premium materials and finishes','Strategic lighting to showcase your products','Interactive spaces and meeting rooms','Professional installation and dismantling','Comprehensive warranty on all elements','Post-exhibition service']} faqsAr={[{q:'ما الفرق بين الأجنحة المخصصة والنمطية؟',a:'الأجنحة المخصصة مصممة بالكامل لعلامتك التجارية تحديداً وتوفر حرية إبداعية كاملة، بينما الأجنحة النمطية تعتمد على نظام هياكل قياسية قابلة لإعادة الاستخدام.'},{q:'هل يمكن إعادة استخدام الجناح المخصص في معارض أخرى؟',a:'نعم، نصمم الأجنحة المخصصة لتكون قابلة للتفكيك والتركيب مرات متعددة مع الحفاظ على جودتها وشكلها.'},{q:'ما الحد الأدنى لمساحة الجناح المخصص؟',a:'عادةً ما تبدأ الأجنحة المخصصة من 18م² وتصل إلى آلاف الأمتار للأجنحة الكبرى.'}]} faqsEn={[{q:'What is the difference between custom and modular booths?',a:'Custom booths are designed entirely for your specific brand providing complete creative freedom, while modular booths rely on a standard reusable frame system.'},{q:'Can a custom booth be reused at other exhibitions?',a:'Yes, we design custom booths to be dismantled and reinstalled multiple times while maintaining their quality and appearance.'},{q:'What is the minimum size for a custom booth?',a:'Custom booths typically start from 18m² and reach thousands of square meters for large-scale stands.'}]} image="https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80" relatedServicesAr={['تصميم أجنحة المعارض','الأجنحة النمطية','تنفيذ الأجنحة']} relatedServicesEn={['Exhibition Stand Design','Modular Booths','Booth Fabrication']} />);
}
